//! Native commands are generated by UniFFI. JSON is confined to the Expo/vault
//! and durable journal boundaries, rather than reinterpreted by each worker.
use crate::MlsError;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Deserialize, Serialize, uniffi::Enum)]
#[serde(rename_all = "lowercase")]
pub enum MediaKind {
    Photo,
    Video,
}

#[derive(Clone, Copy, Debug, PartialEq, Deserialize, Serialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum SendDisposition {
    Retry,
    Blocked,
    Terminal,
}

#[derive(Clone, Debug, Deserialize, Serialize, uniffi::Record)]
pub struct SendFailure {
    pub disposition: SendDisposition,
    pub message: String,
}
impl SendFailure {
    pub(crate) fn from_error(error: MlsError) -> Self {
        match error {
            MlsError::Transport => Self {
                disposition: SendDisposition::Retry,
                message: "The send could not reach the server. Whisp will retry when connected; the queued whisp is preserved.".into(),
            },
            MlsError::Request { status, recovery, .. } => Self {
                disposition: match status {
                    408 | 409 | 425 | 429 | 500..=599 => SendDisposition::Retry,
                    400 | 404 | 410 | 413 | 422 => SendDisposition::Terminal,
                    _ => SendDisposition::Blocked,
                },
                message: recovery,
            },
            other => Self {
                disposition: SendDisposition::Blocked,
                message: format!("{other} The queued whisp is preserved. Reopen Whisp to retry."),
            },
        }
    }
}

/// Failures reported by platform compression/transfer code, without arbitrary
/// exception text that might contain signed URLs, credentials, or media paths.
#[derive(Clone, Copy, uniffi::Enum)]
pub enum SendInterruption {
    Compression,
    Transfer,
    Storage,
}
impl From<SendInterruption> for SendFailure {
    fn from(reason: SendInterruption) -> Self {
        match reason {
            SendInterruption::Compression => Self {
                disposition: SendDisposition::Blocked,
                message: "This photo or video could not be compressed. The original capture is preserved. Reopen Whisp to retry, or capture it again.".into(),
            },
            SendInterruption::Transfer => Self {
                disposition: SendDisposition::Retry,
                message: "The encrypted upload was interrupted. Whisp will retry when connected.".into(),
            },
            SendInterruption::Storage => Self {
                disposition: SendDisposition::Blocked,
                message: "The queued send could not be processed on this device. Check available storage, then reopen Whisp to retry.".into(),
            },
        }
    }
}

#[derive(Debug, Serialize, uniffi::Record)]
pub struct SendUpload {
    pub id: String,
    pub url: String,
    pub file: String,
}

#[derive(Debug, Serialize, uniffi::Enum)]
#[serde(tag = "stage", rename_all = "camelCase")]
pub enum SendStep {
    Compress {
        kind: MediaKind,
        source: String,
        output: String,
    },
    Upload {
        transfer: SendUpload,
    },
    Confirm,
    Continue,
    Sent,
    Failed {
        message: String,
    },
    Paused {
        failure: SendFailure,
    },
}

#[derive(Clone, Copy, Debug, Serialize, uniffi::Enum)]
#[serde(rename_all = "lowercase")]
pub enum SendStatus {
    Uploading,
    Blocked,
    Sent,
    Failed,
}

#[derive(Serialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendJobStatus {
    pub id: String,
    pub kind: MediaKind,
    pub recipients: Vec<String>,
    pub group_id: Option<String>,
    pub status: SendStatus,
    pub error: Option<String>,
    pub created_at: u64,
}

#[derive(uniffi::Record)]
pub struct SendWorkerConfig {
    pub root: String,
    pub device_id: String,
    pub uploadthing_version: String,
}

#[uniffi::export]
pub fn send_worker_config(config: String) -> Result<SendWorkerConfig, MlsError> {
    let c = crate::send_api::SendConfig::parse(&config)?;
    Ok(SendWorkerConfig {
        root: c.root,
        device_id: c.device_id,
        uploadthing_version: c.uploadthing_version,
    })
}
