// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-whisp-mls.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "WhispMlsSpec.h"

@interface WhispMls : NSObject <NativeWhispMlsSpec>
#else
#import <React/RCTBridgeModule.h>

@interface WhispMls : NSObject <RCTBridgeModule>
#endif

@end