// Generated by uniffi-bindgen-react-native
#import "WhispMls.h"
#import <Foundation/Foundation.h>

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeWhispMls'
    */
    class JSI_EXPORT NativeWhispMlsSpecJSI : public ObjCTurboModule {
    public:
        NativeWhispMlsSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_WhispMls_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        // MLS ratchets must never be restored from an older cloud backup.
        NSFileManager *files = [NSFileManager defaultManager];
        NSURL *documents = [[files URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] firstObject];
        NSURL *stateDirectory = [documents URLByAppendingPathComponent:@"mls-v1" isDirectory:YES];
        NSError *error = nil;
        if (!stateDirectory ||
            ![files createDirectoryAtURL:stateDirectory withIntermediateDirectories:YES
                              attributes:@{NSFileProtectionKey: NSFileProtectionComplete} error:&error] ||
            ![stateDirectory setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:&error]) {
            return facebook::jsi::Value(false);
        }
        auto& tm = static_cast<NativeWhispMlsSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = whispmls::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_WhispMls_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = whispmls::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeWhispMlsSpecJSI::NativeWhispMlsSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_WhispMls_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_WhispMls_cleanupRustCrate};
    }
} // namespace uniffi_generated

@implementation WhispMls
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

// Automated testing checks whispmls
// by comparing the whole line here.
/*
- (NSNumber *)multiply:(double)a b:(double)b {
    NSNumber *result = @(whispmls::multiply(a, b));
}
*/

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeWhispMlsSpecJSI>(params);
}
#endif

@end