// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "react-native-whisp-mls.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_chat_whisp_mls_WhispMlsModule and whispmls
// by comparing the whole line here.
/*
Java_chat_whisp_mls_WhispMlsModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return whispmls::multiply(a, b);
}
*/

// Installer coming from WhispMlsModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_chat_whisp_mls_WhispMlsModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return whispmls::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_chat_whisp_mls_WhispMlsModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return whispmls::cleanupRustCrate(*runtime);
}