// Generated by uniffi-bindgen-react-native
#include "react-native-whisp-mls.h"
#include "generated/whisp_mls.hpp"

namespace whispmls {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeWhispMls::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}